Experience_Table:
  Gathering:
  #FARMING
  - "BROWN_MUSHROOM=6"
  - "CACTUS=5"
  - "CARROT=4"
  - "CARROT_ITEM=4"
  - "COCOA=6"
  - "CROPS=4"
  - "MELON=5"
  - "MELON_BLOCK=4"
  - "MELON_SEEDS=4"
  - "POTATO=4"
  - "POTATO_ITEM=4"
  - "RED_MUSHROOM=6"
  - "SEEDS=4"
  - "SPECKLED_MELON=4"
  - "SUGAR_CANE=5"
  - "SUGAR_CANE_BLOCK=5"
  - "WHEAT=4"
  #ORES
  - "COAL_ORE=6"
  - "IRON_ORE=8"
  - "LAPIS_ORE=14"
  - "GOLD_ORE=14"
  - "REDSTONE_ORE=14"
  - "DIAMOND_ORE=18"
  - "EMERALD_ORE=20"
  - "QUARTZ_ORE=24"
  - "CLAY=2"
  #GATHERER
  - "LOG=3"
  - "LOG_2=3"
  - "CLAY=2"
  - "STONE=2"
  - "SANDSTONE=4"
  - "RED_SANDSTONE=4"
  - "SOUL_SAND=10"
  - "GLOWSTONE=14"
  - "SPONGE=25"
  - "DEAD_BUSH=2"
  - "MOB_SPAWNER=40"
  Crafting:
  #COOKING
  - "BAKED_POTATO=4"
  - "BREAD=6"
  - "CAKE=15"
  - "COOKED_BEEF=3"
  - "COOKED_CHICKEN=4"
  - "COOKED_FISH=5"
  - "COOKED_MUTTON=3"
  - "COOKED_RABBIT=4"
  - "COOKIE=10"
  - "GOLDEN_APPLE=100"
  - "GRILLED_PORK=3"
  - "MUSHROOM_SOUP=8"
  - "PUMPKIN_PIE=12"
  - "RABBIT_STEW=10"
  #CRAFTER
  - "ACACIA_DOOR=4"
  - "ACACIA_DOOR_ITEM=4"
  - "ACACIA_FENCE=4"
  - "ACACIA_FENCE_GATE=4"
  - "ACACIA_STAIRS=2"
  - "ANVIL=8"
  - "ARMOR_STAND=3"
  - "BANNER=5"
  - "BED=6"
  - "BIRCH_DOOR_ITEM=4"
  - "BIRCH_FENCE=4"
  - "BIRCH_FENCE_GATE=4"
  - "BIRCH_WOOD_STAIRS=2"
  - "BLAZE_POWDER=15"
  - "BOAT=4"
  - "BOOK=4"
  - "BOOK_AND_QUILL=5"
  - "BOOKSHELF=15"
  - "BOWL=1"
  - "BREWING_STAND_ITEM=20"
  - "BRICK=8"
  - "BRICK_STAIRS=4"
  - "BUCKET=2"
  - "CARPET=2"
  - "CAULDRON_ITEM=8"
  - "CHEST=4"
  - "COBBLE_WALL=1"
  - "COBBLESTONE_STAIRS=1"
  - "DARK_OAK_DOOR_ITEM=4"
  - "DARK_OAK_FENCE=4"
  - "DARK_OAK_FENCE_GATE=4"
  - "DARK_OAK_STAIRS=2"
  - "ENCHANTMENT_TABLE=20"
  - "FENCE=4"
  - "FENCE_GATE=4"
  - "FIREWORK=10"
  - "FLOWER_POT_ITEM=3"
  - "GLASS=1"
  - "IRON_FENCE=4"
  - "ITEM_FRAME=3"
  - "JACK_O_LANTERN=3"
  - "JUNGLE_DOOR_ITEM=4"
  - "JUNGLE_FENCE=4"
  - "JUNGLE_FENCE_GATE=4"
  - "LADDER=2"
  - "NETHER_BRICK=6"
  - "NETHER_BRICK_STAIRS=5"
  - "NETHER_FENCE=5"
  - "PAINTING=2"
  - "QUARTZ_STAIRS=8"
  - "RED_SANDSTONE_STAIRS=3"
  - "SANDSTONE_STAIRS=3"
  - "SEA_LANTERN=25"
  - "SIGN=4"
  - "SMOOTH_BRICK=5"
  - "SMOOTH_STAIRS=4"
  - "SPRUCE_DOOR_ITEM=4"
  - "SPRUCE_FENCE=4"
  - "SPRUCE_FENCE_GATE=4"
  - "SPRUCE_WOOD_STAIRS=2"
  - "STANDING_BANNER=5"
  - "STEP=1"
  - "STONE_SLAB2=1"
  - "TRAP_DOOR=4"
  - "WOODEN_DOOR=4"
  - "WOOD_DOOR=4"
  - "WOOD_STAIRS=2"
  - "WOOD_STEP=1"
  #TINKER
  - "ACTIVATOR_RAIL=6"
  - "COMMAND=10"
  - "COMMAND_MINECART=3"
  - "COMPASS=10"
  - "DAYLIGHT_DETECTOR=15"
  - "DAYLIGHT_DETECTOR_INVERTED=15"
  - "DETECTOR_RAIL=6"
  - "DIODE=5"
  - "DISPENSER=6"
  - "DROPPER=4"
  - "EMPTY_MAP=4"
  - "EXPLOSIVE_MINECART=3"
  - "BEACON=10"
  - "HOPPER=6"
  - "HOPPER_MINECART=3"
  - "IRON_DOOR=4"
  - "IRON_TRAPDOOR=4"
  - "LEVER=2"
  - "MAP=3"
  - "MINECART=5"
  - "NOTE_BLOCK=4"
  - "PISTON_BASE=4"
  - "PISTON_EXTENSION=4"
  - "PISTON_MOVING_PIECE=4"
  - "PISTON_STICKY_BASE=2"
  - "POWERED_MINECART=3"
  - "POWERED_RAIL=6"
  - "RAILS=3"
  - "REDSTONE_COMPARATOR=5"
  - "REDSTONE_COMPARATOR_ON=5"
  - "REDSTONE_COMPARATOR_OFF=5"
  - "REDSTONE_LAMP_ON=8"
  - "REDSTONE_LAMP_OFF=8"
  - "REDSTONE_TORCH_ON=2"
  - "REDSTONE_TORCH_OFF=2"
  - "STONE_BUTTON=1"
  - "STONE_PLATE=1"
  - "STORAGE_MINECART=3"
  - "TNT=6"
  - "TRAPPED_CHEST=3"
  - "TRIPWIRE=2"
  - "TRIPWIRE_HOOK=4"
  - "WATCH=10"
  - "WOOD_BUTTON=1"
  - "WOOD_PLATE=1"
  #BLACKSMITH
  - "CHAINMAIL_BOOTS=5"
  - "CHAINMAIL_CHESTPLATE=8"
  - "CHAINMAIL_HELMET=6"
  - "CHAINMAIL_LEGGINGS=7"
  - "DIAMOND_AXE=20"
  - "DIAMOND_BARDING=30"
  - "DIAMOND_BOOTS=12"
  - "DIAMOND_CHESTPLATE=20"
  - "DIAMOND_HELMET=17"
  - "DIAMOND_HOE=20"
  - "DIAMOND_LEGGINGS=18"
  - "DIAMOND_PICKAXE=20"
  - "DIAMOND_SPADE=20"
  - "DIAMOND_SWORD=20"
  - "ENDER_CHEST=50"
  - "ARROW=1"
  - "BOW=4"
  - "FISHING_ROD=6"
  - "FURNACE=2"
  - "GOLD_AXE=15"
  - "GOLD_BARDING=25"
  - "GOLD_BOOTS=8"
  - "GOLD_CHESTPLATE=15"
  - "GOLD_HELMET=12"
  - "GOLD_HOE=15"
  - "GOLD_LEGGINGS=14"
  - "GOLD_PICKAXE=15"
  - "GOLD_PLATE=2"
  - "GOLD_SPADE=15"
  - "GOLD_SWORD=15"
  - "IRON_AXE=18"
  - "IRON_BARDING=28"
  - "IRON_BOOTS=10"
  - "IRON_CHESTPLATE=18"
  - "IRON_HELMET=15"
  - "IRON_HOE=18"
  - "IRON_LEGGINGS=16"
  - "IRON_PICKAXE=18"
  - "IRON_PLATE=3"
  - "IRON_SPADE=18"
  - "IRON_SWORD=18"
  - "LEATHER_BOOTS=5"
  - "LEATHER_CHESTPLATE=10"
  - "LEATHER_HELMET=7"
  - "LEATHER_LEGGINGS=9"
  - "SADDLE=15"
  - "STONE_AXE=10"
  - "STONE_HOE=10"
  - "STONE_PICKAXE=10"
  - "STONE_SPADE=10"
  - "STONE_SWORD=10"
  - "WOOD_AXE=5"
  - "WOOD_PICKAXE=5"
  - "WOOD_SPADE=5"
  - "WOOD_HOE=5"
  - "WOOD_SWORD=5"
  - "WORKBENCH=5"
  Entities:
  #KILLING
  - "BAT=8"
  - "BLAZE=50"
  - "CAVE_SPIDER=15"
  - "CHICKEN=5"
  - "COW=4"
  - "CREEPER=20"
  - "ENDER_DRAGON=500"
  - "ENDERMAN=50"
  - "ENDERMITE=10"
  - "GHAST=40"
  - "GIANT=50"
  - "GUARDIAN=100"
  - "HORSE=5"
  - "IRON_GOLEM=10"
  - "MAGMA_CUBE=10"
  - "MUSHROOM_COW=5"
  - "OCELOT=15"
  - "PIG=4"
  - "PIG_ZOMBIE=20"
  - "PLAYER=50"
  - "RABBIT=5"
  - "SHEEP=4"
  - "SILVERFISH=10"
  - "SKELETON=15"
  - "SQUID=5"
  - "SPIDER=15"
  - "VILLAGER=5"
  - "WITCH=100"
  - "WOLF=8"
  - "ZOMBIE=12"
Custom_Items:
# JUNK(ChatColor.GRAY),
# COMMON(ChatColor.WHITE),
# UNCOMMON(ChatColor.GREEN),
# RARE(ChatColor.BLUE),
# MYTHIC(ChatColor.DARK_PURPLE),
# LEGENDARY(ChatColor.GOLD);
  acacia_door_item:
    Material: 'ACACIA_DOOR_ITEM'
    Name: 'Acacia door'
    Description:
    - "A door made from Acacia."
    - "Opens with a nice squeek."
    Replace_Default: true
  acacia_fence:
    Material: 'ACACIA_FENCE'
    Name: 'Acacia fence'
    Description:
    - "Fence made from Acacia."
    Replace_Default: true
  acacia_fence_gate:
    Material: 'ACACIA_FENCE_GATE'
    Name: 'Acacia Fence Gate'
    Description:
    - "An Acacia gate that fits"
    - "nicely inbetween fence."
    Replace_Default: true
  acacia_stairs:
    Material: 'ACACIA_STAIRS'
    Name: 'Acacia Stairs'
    Description:
    - "Wooden stairs made from"
    - "Acacia planks."
    Replace_Default: true
  activator_rail:
    Material: 'ACTIVATOR_RAIL'
    Name: 'Activator Rail'
    Description:
    - "Modified minecart rails with"
    - "varying effecs depending on"
    - "the minecart that activates it."
    Replace_Default: true
    Rarity: 'RARE'
  anvil:
    Material: 'ANVIL'
    Name: 'Standard Anvil'
    Description:
    - "A common anvil used by"
    - "blacksmiths to repair"
    - "equipment."
    Replace_Default: true
    Rarity: 'UNCOMMON'
  apple:
    Material: 'APPLE'
    Name: 'Apple'
    Description:
    - "Not too soft, not too"
    - "hard and juicy as you"
    - "bite into it!"
    Replace_Default: true
  armor_stand:
    Material: 'ARMOR_STAND'
    Name: 'Armor Stand'
    Description:
    - "Display your past adventures"
    - "on these stands!"
    Replace_Default: true
    Rarity: 'UNCOMMON'
  arrow:
    Material: 'ARROW'
    Name: 'Iron Arrow'
    Description:
    - "Very commonly seen with"
    - "and used by archers around"
    - "the world."
    Replace_Default: true
    Rarity: LEGENDARY
  baked_potato:
    Material: 'BAKED_POTATO'
    Name: 'Baked Potato'
    Description:
    - "Also known as jacket potato,"
    - "these potatoes are baked"
    - "which makes them fluffy on the"
    - "inside and crispy on the outside."
    Replace_Default: true
  banner:
    Material: 'BANNER'
    Name: 'Banner'
    Description:
    - "Show your affiliation from"
    - "afar with these huge banners."
    Replace_Default: true
    Rarity: 'UNCOMMON'
  beacon:
    Material: 'BEACON'
    Name: 'Beacon'
    Description:
    - "A position marked with this"
    - "can be found from anywhere"
    - "with a clear sky."
    Replace_Default: true
    Rarity: 'RAE'
  bed:
    Material: 'BED'
    Name: 'Simple Bed'
    Description:
    - "Nice and fluffy!"
    - "Doesn't work as trampoline,"
    - "sadly enough..."
    Replace_Default: true
    Rarity: 'UNCOMMON'
  birch_door_item:
    Material: 'BIRCH_DOOR_ITEM'
    Name: 'Birch Door'
    Description:
    - "A door made from Birch."
    - "Opens with a nice squeek."
    Replace_Default: true
  birch_fence:
    Material: 'BIRCH_FENCE'
    Name: 'Birch Fence'
    Description:
    - "Fence made from Birch."
    Replace_Default: true
  birch_fence_gate:
    Material: 'ACACIA_FENCE_GATE'
    Name: 'Acacia Fence Gate'
    Description:
    - "A Birch gate that fits"
    - "nicely inbetween fence."
    Replace_Default: true
  birch_wood_stairs:
    Material: 'BIRCH_WOOD_STAIRS'
    Name: 'Birch Stairs'
    Description:
    - "Wooden stairs made from"
    - "Birch planks."
    Replace_Default: true
  blaze_powder:
    Material: 'BLAZE_POWDER'
    Name: 'Blaze Powder'
    Description:
    - "The remains of a blaze"
    - "rod. Seemingly floating"
    - "away by the heat it"
    - "still generates."
    Replace_Default: true
    Rarity: 'RARE'
  blaze_rod:
    Material: 'BLAZE_ROD'
    Name: 'Blaze Rod'
    Description:
    - "One of the many rods"
    - "floating around a blaze."
    - "Generates blazing heat."
    Replace_Default: true
    Rarity: 'RARE'
  boat:
    Material: 'BOAT'
    Name: 'Boat'
    Description:
    - "It's like walking on water!"
    - "Except not as cool..."
    Replace_Default: true
  bone:
    Material: 'BONE'
    Name: 'Bone'
    Description:
    - "Who knows from what creature"
    - "this originally was?"
    - "Very tasty for dogs, nonetheless."
    Replace_Default: true
  book:
    Material: 'BOOK'
    Name: 'Book'
    Description:
    - "An empty book."
    - "Not very useful as of now..."
    Replace_Default: true
  book_and_quill:
    Material: 'BOOK_AND_QUILL'
    Name: 'Book and Quill'
    Description:
    - "This one has a quill!"
    - "Now go and write the next"
    - "hit. What about this:"
    - "50 Shades of Blocks?"
    Replace_Default: true
    Rarity: 'UNCOMMON'
  bookshelf:
    Material: 'BOOKSHELF'
    Name: 'Bookshelf'
    Description:
    - "Let's see..."
    - "Game of Blocks,"
    - "Nether Star Wars,"
    - "Attack On Endermen and"
    - "... Ah, who cares?"
    Replace_Default: true
    Rarity: 'UNCOMMON'
  bow:
    Material: 'BOW'
    Name: 'Oak Bow'
    Description:
    - "Nothing special, but"
    - "it serves it purpose."
    Replace_Default: true
  bread:
    Material: 'BREAD'
    Name: 'Bread'
    Description:
    - "One of the many rods"
    - "floating around a blaze."
    - "Generates blazing heat."
    Replace_Default: true
  brick:
    Material: 'BRICK'
    Name: 'Brick'
    Description:
    - "Very brittle, yet very"
    - "versatile in uses."
    - "Has a unique red color to it."
    Replace_Default: true
    Rarity: 'UNCOMMON'
  brick_stairs:
    Material: 'BRICK_STAIRS'
    Name: 'Brick Stairs'
    Description:
    - "Stairs made from bricks."
    - "Has the unique pattern seen"
    - "in all brick materials."
    Replace_Default: true
  brown_mushroom:
    Material: 'BROWN_MUSHROOM'
    Name: 'Brown Mushroom'
    Description:
    - "Grows in dark places deep down."
    - "Can be used a variety of ways."
    Replace_Default: true
  bucket:
    Material: 'BUCKET'
    Name: 'Iron Bucket'
    Description:
    - "An iron bucket that somehow"
    - "doesn't smelt when filled"
    - "with lava..."
    Replace_Default: true
  cactus:
    Material: 'CACTUS'
    Name: 'Cactus'
    Description:
    - "Ouch! Be careful or it"
    - "sticks right in your finger!"
    Replace_Default: true
  cake:
    Material: 'CAKE'
    Name: 'Cake'
    Description:
    - "No longer a lie."
    - "It's so delicious and moist!"
    Replace_Default: true
    Rarity: 'UNCOMMON'
  carrot_item:
    Material: 'CARROT_ITEM'
    Name: 'Carrot'
    Description:
    - "Said to be good for your eyes."
    - "Why did he need a doc anyway?"
    Replace_Default: true
    Rarity: 'UNCOMMON'
  carrot_stick:
    Material: 'CARROT_STICK'
    Name: 'Carrot Stick'
    Description:
    - "Go forth, my pink steed!"
    - "- Sir Steveworth's last words"
    - "as he jumped off the cliff."
    Replace_Default: true
    Rarity: 'UNCOMMON'
  cauldron_item:
    Material: 'CAULDRON_ITEM'
    Name: 'Cauldron'
    Description:
    - "Some dirt, some grass,"
    - "random plants, and you have"
    - "the perfect stew!"
    Replace_Default: true
    Rarity: 'RARE'
  dirt:
    Material: 'DIRT'
    Name: 'Dirt'
    Description:
    - "Found everywhere around"
    - "the world, like under"
    - "your boot!"
    Replace_Default: true
    Rarity: 'JUNK'