name: RPG
main: com.hangout.rpg.Plugin
version: 1.0
depend: [CorePlugin]
commands:
  guild:
    description: Commands that are used for managing guilds
    usage: "/guild"
  rpgtext:
    description: Commands that are used with clickable text
    usage: "/text"