package com.hangout.rpg.player;

public enum PlayerStat {
	DAMAGE_RANGED,
	DAMAGE_MELEE,
	DROP_INCREASE_ORE,
	DROP_INCREASE_CROP,
	DROP_AMOUNT_ORE,
	DROP_AMOUNT_CROP,
	HEALTH,
	MOVESPEED,
	POISON_CHANCE,
	POISON_DURATION,
	HOE_DURABILITY,
	SPADE_DURABILITY,
	PICKAXE_DURABILITY,
	AXE_DURABILITY,
	FISHINGROD_DURABILITY,
	FISHING_CATCH_INCREASE,
	FISHING_CATCH_AMOUNT,
	FISHING_SPECIAL_CATCH,
	REPUTATION_ON_KILL
}